galaxy_info:
  author: denav
  description: This role configures and starts docker-composed based teamspeak servers.

  # If the issue tracker for your role is not on github, uncomment the
  issue_tracker_url: https://github.com/DenAV/ansible-teamspeak-docker/issues

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - server
    - development
    - webserver
    - docker
    - teamspeak

dependencies: []
